# -*- coding: utf-8 -*-
"""P2 -2022.2 - App Web

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HMIovgzO6XYBrqJGtUuJLo871-h9pN0-

##Aplicação Web
"""

import streamlit as st
import pandas as pd
import pickle
import os

filename = os.path.join(os.path.dirname(__file__), 'modelo_treinado.pkl')
model = pickle.load(open(filename, 'rb'))

# Carregando o modelo treinado
model = pickle.load(open(filename, 'rb'))

# Título da página
st.title('Predição de Rotatividade de Funcionários')

# Descrição do problema
st.markdown('Esta aplicação prevê a rotatividade de funcionários de uma empresa baseada em algumas informações pessoais e profissionais.')

# Criação do formulário
with st.form(key='employee_form'):
    # Criando as colunas do formulário
    col1, col2 = st.beta_columns(2)

    # Adicionando os campos ao formulário
    with col1:
        monthly_income = st.number_input('Renda Mensal (R$):', min_value=0)
        total_working_years = st.number_input('Total de Anos Trabalhados:', min_value=0)
        years_at_company = st.number_input('Anos na Empresa:', min_value=0)
        years_in_current_role = st.number_input('Anos na Posição Atual:', min_value=0)

    with col2:
        job_level = st.selectbox('Nível do Cargo:', ['1', '2', '3', '4', '5'])
        job_involvement = st.selectbox('Envolvimento com o Trabalho:', ['1', '2', '3', '4'])
        job_satisfaction = st.selectbox('Satisfação com o Trabalho:', ['1', '2', '3', '4'])
        stock_option_level = st.selectbox('Nível de Opções de Ações:', ['0', '1', '2', '3'])

    # Adicionando os campos de Business Travel, Job Role, Marital Status e OverTime
    business_travel = st.selectbox('Frequência de Viagens a Negócios:', ['Travel_Rarely', 'Travel_Frequently', 'Non-Travel'])
    job_role = st.selectbox('Cargo:', ['Sales Executive', 'Research Scientist', 'Laboratory Technician', 'Manufacturing Director', 'Healthcare Representative', 'Manager', 'Sales Representative', 'Research Director', 'Human Resources'])
    marital_status = st.selectbox('Estado Civil:', ['Married', 'Single', 'Divorced'])
    over_time = st.selectbox('Trabalha Horas Extras?', ['Yes', 'No'])

    # Botão para submeter os dados
    submit_button = st.form_submit_button(label='Prever')
